# Generated by Django 6.0.1 on 2026-03-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homestay',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.homestay')),
            ],
        ),
    ]
