# Generated by Django 5.2.11 on 2026-03-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0002_homestay_image_alter_homestay_description_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homestay',
            name='address',
        ),
        migrations.RemoveField(
            model_name='homestay',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='homestay',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
