# Generated by Django 5.2.12 on 2026-03-09 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('status', models.CharField(choices=[('empty', 'Empty'), ('booked', 'Booked')], default='empty', max_length=20)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homestay.homestay')),
            ],
        ),
    ]
