# Generated by Django 5.2.12 on 2026-03-09 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0005_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='total_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='homestay.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=200),
        ),
    ]
