# Generated by Django 6.0.1 on 2026-03-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0006_rename_price_booking_total_price_booking_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homestay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homestay.homestay')),
            ],
        ),
    ]
