# Generated by Django 6.0.1 on 2026-04-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0009_homestay_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
