# Generated by Django 6.0.1 on 2026-04-06 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homestay', '0010_homestay_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='homestay',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
